name: Build-And-Deploy
description: builds and deploys the microservice-demo using skaffold
inputs:
  environment:
    description: Which environment to deploy to.  Valid values are `dev`, `staging`, and `prod`.
    required: true
  project-id:
    description: Project ID of the GCP project
    required: true
  workload-identity-provider:
    description: Workload identity provider to use to authenticate.
    required: true
runs:
  using: "composite"
  steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: '${{ inputs.workload-identity-provider }}'
        service_account: 'microservices-otel-demo@${{ inputs.project-id }}.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: install dependencies
      shell: bash
      run: |
        chmod +x .github/workflows/install-dependencies.sh
        .github/workflows/install-dependencies.sh
      
    - name: connect to cluster
      shell: bash
      run: gcloud container clusters get-credentials ${{ inputs.environment }}-microservices-otel-demo --zone us-central1-a --project ${{ inputs.project-id }}
    - name: configure docker cli to authenticate to GCR
      shell: bash
      run: gcloud auth configure-docker -q
    - name: build and deploy
      shell: bash
      run: skaffold run --default-repo=gcr.io/${{ inputs.project-id }}
    - name: verify pods are running
      shell: bash
      run: kubectl get pods
