name: "Build and Deploy"

on:
  workflow_dispatch:

jobs:
  build-deploy:
    if: contains('svetlanabrennan,TylerHelmuth,jack-berg,nrcventura,martinkuba,alanwest,reese-lee', github.actor)
    permissions:
        contents: 'read'
        id-token: 'write'
    runs-on: ubuntu-latest
    environment: development
    env:
      OTEL_EXPORTER_OTLP_ENDPOINT: https://staging-otlp.nr-data.net:4317
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: https://staging-otlp.nr-data.net:4317
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: https://staging-otlp.nr-data.net:4317
      OTEL_EXPORTER_OTLP_ENDPOINT_INFINITE_TRACING: ${{ secrets.INFINITE_TRACING_ENDPOINT }}"
      OTEL_EXPORTER_OTLP_HEADERS: "api-key: ${{ secrets.API_KEY }}"
      NEW_RELIC_API_KEY: ${{ secrets.API_KEY }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.API_KEY }}
      NEW_RELIC_HOST: staging-collector.newrelic.com
    steps:
    - uses: actions/checkout@v2
    - name: Build-And-Deploy
      uses: ./.github/actions/build-and-deploy
      with:
        environment: "dev"
